version: "2"

services:
    web_console:
        image: bitbull/docker-exec-web-console
        environment:
        - 'CONTEXT_PATH=/web-console/'
        read_only: true
        restart: always
        volumes:
        - ./docker-exec-web-console/index.html:index.html
        - /var/run/docker.sock:/var/run/docker.sock
    nginx:
        image: nginx:latest
        read_only: true
        restart: always
        ports:
        - 443:443
        volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
        - ./localhost.crt:/etc/nginx/localhost.crt:ro
        - ./localhost.key:/etc/nginx/localhost.key:ro
        - ./static/scripts/proxyport.js:/etc/nginx/proxyport.js
        - /var/cache/nginx/
        - /var/run/
        - ./logs/:/logs/
